---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 8092
    targetPort: 80
    name: http

---
apiVersion: apps/v1

kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
     labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ashwatha12/apache1-file
        ports:
        - containerPort: 80
        



